pull_request_rules:
  - name: Backport changes to v3.x
    conditions:
      - label = backport-potential
    actions:
      backport:
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}
        merge_conflict_style: diff3
        branches:
          - v3.x

  - name: Automatically merge backport PRs
    conditions:
      - author = mergify[bot]
      - base ~= ^mergify/bp/
      - head ~= ^v3\.x
      - check-success = 🚦 Check
    actions:
      label:
        add:
          - backport
      merge:
        method: squash
