# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

AuthType=auth/munge
DbdHost=accounting
SlurmUser=slurm
PidFile=/run/slurmdbd.pid
StorageType=accounting_storage/mysql
StorageHost=database
StorageUser=slurm
StorageLoc=slurm_acct_db
