# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

ClusterName=mqt-core
SlurmctldHost=controller(controller-cluster)
SlurmUser=slurm
AuthType=auth/munge
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=accounting
AccountingStorageEnforce=associations
AccountingStorageTRES=license/mqt.ddsim.default,license/mqt.sc.default

ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup,task/affinity
JobAcctGatherType=jobacct_gather/cgroup
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory
DefMemPerCPU=1024
PrologFlags=Contain

SchedulerType=sched/backfill
ReturnToService=2
SlurmdParameters=config_overrides
SlurmctldParameters=reconfig_on_restart

Licenses=mqt.ddsim.default:2,mqt.sc.default:1

MaxNodeCount=128
NodeName=DEFAULT CPUs=2 Boards=1 SocketsPerBoard=1 CoresPerSocket=2 ThreadsPerCore=1 RealMemory=2048 State=UNKNOWN
NodeName=qan-iqm NodeHostname=qan-iqm NodeAddr=qan-iqm-cluster Feature=qan,iqm
NodeName=qan-braket NodeHostname=qan-braket NodeAddr=qan-braket-cluster Feature=qan,braket
NodeSet=classical Feature=classical
PartitionName=DEFAULT MaxTime=INFINITE State=DOWN
PartitionName=compute Nodes=classical Default=YES
PartitionName=iqm Nodes=qan-iqm
PartitionName=braket Nodes=qan-braket
