# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

"""Interoperability tests for QIR generated by the Python compiler API."""

from __future__ import annotations

import pytest

from mqt.core.mlir import OutputFormat, QIRProfile, QIRProgram, compile_program

qirrunner = pytest.importorskip("qirrunner")


def _compile_and_run(qasm: str, *, shots: int = 1) -> tuple[QIRProgram, str]:
    """Compile OpenQASM to QIR Base Profile bitcode and execute it.

    Returns:
        The generated QIR program and the collected output records.
    """
    qir = compile_program(qasm, output=OutputFormat.QIR_BASE)
    assert qir.profile is QIRProfile.BASE

    output = qirrunner.OutputHandler()
    qirrunner.run_bytes(qir.to_bitcode(), shots=shots, rng_seed=7, output_fn=output.handle)
    return qir, output.get_output()


def _recorded_bitstrings(output: str, *, width: int) -> list[str]:
    """Extract one bit string per shot from labeled QIR output records.

    Returns:
        The recorded bit strings in execution order.
    """
    bitstrings = []
    for shot in output.split("START\n")[1:]:
        bits = [line.split("\t")[2] for line in shot.splitlines() if line.startswith("OUTPUT\tRESULT\t")]
        assert len(bits) == width
        bitstrings.append("".join(bits))
    return bitstrings


def test_qirrunner_executes_compiled_bell_program() -> None:
    """Execute a compiler-generated Base Profile program through qirrunner."""
    qir, output = _compile_and_run(
        """OPENQASM 3.0;
include "stdgates.inc";
qubit[2] q;
h q[0];
ctrl @ x q[0], q[1];
bit[2] c = measure q;
""",
        shots=32,
    )

    assert "@__quantum__qis__cx__body" in qir.llvm_ir
    assert "METADATA\tqir_profiles\tbase_profile" in output
    assert set(_recorded_bitstrings(output, width=2)) == {"00", "11"}


@pytest.mark.parametrize(
    ("inactive_control", "expected"),
    [
        pytest.param(None, "111", id="all-controls-active"),
        pytest.param(0, "010", id="first-control-inactive"),
        pytest.param(1, "100", id="second-control-inactive"),
    ],
)
def test_qirrunner_executes_native_two_control_qis(inactive_control: int | None, expected: str) -> None:
    """Execute the dedicated two-control X instruction through qirrunner."""
    initialization = "\n".join(f"x q[{control}];" for control in range(2) if control != inactive_control)
    qir, output = _compile_and_run(
        f"""OPENQASM 3.0;
include "stdgates.inc";
qubit[3] q;
{initialization}
ctrl(2) @ x q[0], q[1], q[2];
bit[3] c = measure q;
"""
    )

    assert "@__quantum__qis__ccx__body" in qir.llvm_ir
    assert _recorded_bitstrings(output, width=3) == [expected]


@pytest.mark.parametrize(
    ("inactive_control", "expected"),
    [
        pytest.param(None, "1111", id="all-controls-active"),
        pytest.param(0, "0110", id="first-control-inactive"),
        pytest.param(1, "1010", id="second-control-inactive"),
        pytest.param(2, "1100", id="third-control-inactive"),
    ],
)
def test_qirrunner_executes_generic_multi_control_qis(inactive_control: int | None, expected: str) -> None:
    """Execute a three-control X specialization through qirrunner."""
    initialization = "\n".join(f"x q[{control}];" for control in range(3) if control != inactive_control)
    qir, output = _compile_and_run(
        f"""OPENQASM 3.0;
include "stdgates.inc";
qubit[4] q;
{initialization}
ctrl(3) @ x q[0], q[1], q[2], q[3];
bit[4] c = measure q;
"""
    )

    assert "@__quantum__qis__x__ctl" in qir.llvm_ir
    assert "@__quantum__rt__array_create_1d" in qir.llvm_ir
    assert "METADATA\tqir_profiles\tbase_profile" in output
    assert _recorded_bitstrings(output, width=4) == [expected]
