name: Templating
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
      - name: Render template
        uses: munich-quantum-toolkit/.github/templating@templating
        with:
          package-name: core2
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update template"
          git push origin templating
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
