name: Templating
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-latest
    steps:
      - uses: munich-quantum-toolkit/.github/templating@templating
        with:
          package-url: https://github.com/munich-quantum-toolkit/core/test
